version: "3"
services:
  webapi:
    build: .
    restart: on-failure
    env_file:
      - ./.env
      - ./.env.secret
    command: python3 manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    depends_on:
      - db
      - minio
  db:
    image: "postgres:10.3-alpine"
    restart: always
    env_file:
        - ./.env.secret
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
  minio:
    image: minio/minio
    restart: on-failure
    env_file:
      - ./.env.secret
    # entrypoint: sh
    # command: -c "mkdir -p /data/cog && /usr/bin/minio server /data"
    command: minio server /data
    ports:
      - "9001:9000"
    volumes:
      - minio-data:/data

volumes:
  postgres-data:
  minio-data: